Abort old builds for a branches
Deepomatic/dmake pull request #517
Opened 2022-02-23 10:46 UTC by S4ckBr

## Description
Abort old builds on Jenkins jobs

What it does:

- Abort all previous builds for branches present in the comma separated list defined by `DEFAULT_ABORT_OLD_BUILDS_ON_BRANCHES`.
- It can be deactivated if the `DEFAULT_ABORT_OLD_BUILDS_ON_BRANCHES` list is empty.

2022-02-23 10:50 UTC, thomas-riccardi requested changes
seems good overall, some cleanup to do

2022-02-23 10:50 UTC, thomas-riccardi commented on dmake/templates/jenkins/Jenkinsfile
> +    default_abort_old_builds_on_branches="" // empty list: disabled
nit
```suggestion
    default_abort_old_builds_on_branches='' // empty list: disabled
```

2022-02-23 10:50 UTC, thomas-riccardi commented on dmake/templates/jenkins/Jenkinsfile
> +               description: 'Abort old builds for a branches, comma separated list.'),
```suggestion
               description: 'Abort old builds for these branches, comma separated list.'),
```

2022-02-23 10:50 UTC, thomas-riccardi commented on dmake/templates/jenkins/Jenkinsfile
> +}
let's merge this block with the one for PR condition: just combine the 2 `if`

2022-02-24 17:42 UTC, S4ckBr commented
On a PR branch old build is correctly aborted.
On the main branch, if `DEFAULT_ABORT_OLD_BUILDS_ON_BRANCHES` is empty, nothing is triggered.
The old build is aborted when I set `DEFAULT_ABORT_OLD_BUILDS_ON_BRANCHES='main'`.
On a new branch, nothing is triggered if `DEFAULT_ABORT_OLD_BUILDS_ON_BRANCHES` is empty.
The old build is aborted when `DEFAULT_ABORT_OLD_BUILDS_ON_BRANCHES` is corretly set.

2022-02-24 18:07 UTC, thomas-riccardi approved these changes
code & tests LGTM

2022-02-28 12:23 UTC, merged